### ISSUE TITLE
Unclear meaning of toggle

### ISSUE THREAD

**Issue by srozga** [Microsoft/ConversationLearner-UI#599]
This is more of a question rather than feature request. What is the meaning of the toggle between the API_LOCAL call name and the require entity name? It seems to change the entity text into "$QuoteItem". Is this the equivalent of the cosmetic LUIS toggle between entity/token view or something else?
![image](https://user-images.githubusercontent.com/1940385/41247406-e9c61274-6d7b-11e8-9a31-26ca20f914c2.png)

**Comment by LarsLiden** [comment]
Correct, it's simply a visualization convenience to toggle the view between showing the Entity names and substituted Entity values.   It has not impact on training.
