### ISSUE TITLE
Unable to edit entity extraction in trained dialog first step

### ISSUE THREAD

**Issue by srozga** [Microsoft/ConversationLearner-UI#605]
**Describe the bug**
I have added a new entity and need to modify a number of trained dialogs to recognize this entity. When I go into a trained dialog and click on the initial utterance, the train dialog pop up closes and if I click on the trained dialog again, I get an error window.

**To Reproduce**
1. Click on an existing multi turn trained dialog.
2. Click on the first utterance in the list. My assumption is that this would allow me to highlight where a new entity should be recognized.
3. The popup closes.
4. Click on the same multi turn trained dialog again.
5. The popup comes up but there's also an error window on the side with the text FETCH_HISTORY_ASYNC Failed
TypeError
Cannot read property 'split' of undefined.
6. Incidentally, the X or Close button do not work. I have to refresh the window to get it back to working order.

**Expected behavior**
I should be able to edit the entities recognized in the initial utterance.

**Screenshots**
![image](https://user-images.githubusercontent.com/1940385/41412585-830f4836-6fae-11e8-97c5-e6232f03e240.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 67.0.3396.87 (Official Build) (64-bit)
 - I'm using latest Samples Repo and pointing at version 0.269.2 of SDK.

**Comment by LarsLiden** [comment]
I'm unable to repro this with the given description.   Can you share the text the was tagged and the types of entities that it was tagged with?  Maybe a screen shot?

**Comment by srozga** [comment]
Hmm. I have 11 entities and a bunch of different dialogs here. Could I perhaps email you the export?

**Comment by LarsLiden** [comment]
Sounds good.  You should have my email, correct?

**Comment by LarsLiden** [comment]
Repro'd.  Investigating

**Comment by mattmazzola** [comment]
Fixed by https://github.com/Microsoft/ConversationLearner-UI/pull/613.
